-- SLMS views extracted from the live schema snapshot.
-- Run after create_tables.sql and before procedures/functions.

USE slms;

-- ============================================================================

-- ---- vw_assessment_status ----
CREATE ALGORITHM=UNDEFINED DEFINER=`vincentchanayire`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_assessment_status` AS select `e`.`StudentID` AS `StudentID`,`a`.`AssessmentID` AS `AssessmentID`,`a`.`AssessmentName` AS `AssessmentName`,`a`.`CourseID` AS `CourseID`,`a`.`DueDate` AS `DueDate`,`sub`.`SubmissionID` AS `SubmissionID`,case when `sub`.`SubmissionID` is not null then 'Submitted' when `a`.`DueDate` < curdate() then 'Past-Due' else 'Upcoming' end AS `Status` from ((`slms`.`enrollment` `e` join `slms`.`assessment` `a` on(`e`.`CourseID` = `a`.`CourseID`)) left join `slms`.`submission` `sub` on(`sub`.`AssessmentID` = `a`.`AssessmentID` and `sub`.`StudentID` = `e`.`StudentID` and `sub`.`IsActive` = 1));

-- ---- vw_attendance_summary ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_attendance_summary` AS select `st`.`StudentID` AS `StudentID`,`st`.`F_Name` AS `F_Name`,`st`.`L_Name` AS `L_Name`,`c`.`CourseID` AS `CourseID`,`c`.`CourseName` AS `CourseName`,sum(case when `att`.`Status` = 'Present' then 1 else 0 end) AS `TimesPresent`,sum(case when `att`.`Status` = 'Absent' then 1 else 0 end) AS `TimesAbsent`,sum(case when `att`.`Status` = 'Late' then 1 else 0 end) AS `TimesLate`,count(0) AS `TotalSessions`,round(sum(case when `att`.`Status` = 'Present' then 1 else 0 end) * 100.0 / count(0),2) AS `AttendanceRate` from (((`slms`.`attendance` `att` join `slms`.`timetable` `t` on(`att`.`TimetableID` = `t`.`TimetableID`)) join `slms`.`course` `c` on(`t`.`CourseID` = `c`.`CourseID`)) join `slms`.`student` `st` on(`att`.`StudentID` = `st`.`StudentID`)) group by `st`.`StudentID`,`st`.`F_Name`,`st`.`L_Name`,`c`.`CourseID`,`c`.`CourseName`;

-- ---- vw_below_class_average ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_below_class_average` AS select `y`.`CourseID` AS `CourseID`,`y`.`CourseName` AS `CourseName`,`y`.`StudentID` AS `StudentID`,`y`.`F_Name` AS `F_Name`,`y`.`L_Name` AS `L_Name`,`y`.`StudentAvg` AS `StudentAvg`,avg(`y`.`StudentAvg`) over ( partition by `y`.`CourseID`) AS `ClassAvg` from (select `c`.`CourseID` AS `CourseID`,`c`.`CourseName` AS `CourseName`,`st`.`StudentID` AS `StudentID`,`st`.`F_Name` AS `F_Name`,`st`.`L_Name` AS `L_Name`,avg(`sub`.`Score`) AS `StudentAvg` from (((`slms`.`submission` `sub` join `slms`.`assessment` `a` on(`sub`.`AssessmentID` = `a`.`AssessmentID`)) join `slms`.`course` `c` on(`a`.`CourseID` = `c`.`CourseID`)) join `slms`.`student` `st` on(`sub`.`StudentID` = `st`.`StudentID`)) where `sub`.`IsActive` = 1 group by `c`.`CourseID`,`c`.`CourseName`,`st`.`StudentID`,`st`.`F_Name`,`st`.`L_Name`) `y`;

-- ---- vw_courses_without_assessments ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_courses_without_assessments` AS select distinct `c`.`CourseID` AS `CourseID`,`c`.`CourseName` AS `CourseName`,`c`.`CourseCode` AS `CourseCode` from (`slms`.`course` `c` left join `slms`.`assessment` `a` on(`c`.`CourseID` = `a`.`CourseID`)) where `a`.`AssessmentID` is null;

-- ---- vw_course_enrollment_ranking ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_course_enrollment_ranking` AS select `c`.`CourseID` AS `CourseID`,`c`.`CourseName` AS `CourseName`,count(`e`.`StudentID`) AS `EnrolledStudents`,rank() over ( order by count(`e`.`StudentID`) desc) AS `EnrollmentRank` from (`slms`.`course` `c` join `slms`.`enrollment` `e` on(`c`.`CourseID` = `e`.`CourseID`)) group by `c`.`CourseID`,`c`.`CourseName`;

-- ---- vw_course_grades ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_course_grades` AS select `e`.`StudentID` AS `StudentID`,`st`.`F_Name` AS `F_Name`,`st`.`L_Name` AS `L_Name`,`a`.`CourseID` AS `CourseID`,`a`.`AssessmentID` AS `AssessmentID`,`a`.`AssessmentName` AS `AssessmentName`,`a`.`AssessmentCategory` AS `AssessmentCategory`,`a`.`MaxScore` AS `MaxScore`,`sub`.`Score` AS `Score`,`sub`.`SubmissionID` AS `SubmissionID`,case `a`.`AssessmentCategory` when 'Midsem' then 20 when 'Final' then 40 else (100 - if(exists(select 1 from `slms`.`assessment` `a2` where `a2`.`CourseID` = `a`.`CourseID` and `a2`.`AssessmentCategory` = 'Midsem' limit 1),20,0) - if(exists(select 1 from `slms`.`assessment` `a2` where `a2`.`CourseID` = `a`.`CourseID` and `a2`.`AssessmentCategory` = 'Final' limit 1),40,0)) / nullif((select count(0) from `slms`.`assessment` `a3` where `a3`.`CourseID` = `a`.`CourseID` and `a3`.`AssessmentCategory` = 'Regular'),0) end AS `Weight` from (((`slms`.`assessment` `a` join `slms`.`enrollment` `e` on(`e`.`CourseID` = `a`.`CourseID`)) join `slms`.`student` `st` on(`st`.`StudentID` = `e`.`StudentID`)) left join `slms`.`submission` `sub` on(`sub`.`AssessmentID` = `a`.`AssessmentID` and `sub`.`StudentID` = `e`.`StudentID` and `sub`.`IsActive` = 1));

-- ---- vw_course_performance_ranking ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_course_performance_ranking` AS select `c`.`CourseID` AS `CourseID`,`c`.`CourseName` AS `CourseName`,round(avg(`sub`.`Score` * 100.0 / `a`.`MaxScore`),1) AS `AvgScorePct`,rank() over ( order by avg(`sub`.`Score` * 100.0 / `a`.`MaxScore`)) AS `LowPerformanceRank` from ((`slms`.`submission` `sub` join `slms`.`assessment` `a` on(`sub`.`AssessmentID` = `a`.`AssessmentID`)) join `slms`.`course` `c` on(`a`.`CourseID` = `c`.`CourseID`)) where `sub`.`IsActive` = 1 group by `c`.`CourseID`,`c`.`CourseName`;

-- ---- vw_course_roster ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_course_roster` AS select `c`.`CourseID` AS `CourseID`,`c`.`CourseName` AS `CourseName`,`l`.`F_Name` AS `LecturerFirstName`,`l`.`L_Name` AS `LecturerLastName`,`st`.`StudentID` AS `StudentID`,`st`.`F_Name` AS `StudentFirstName`,`st`.`L_Name` AS `StudentLastName`,`e`.`EnrollmentDate` AS `EnrollmentDate` from (((`slms`.`enrollment` `e` join `slms`.`course` `c` on(`e`.`CourseID` = `c`.`CourseID`)) join `slms`.`lecturer` `l` on(`c`.`LecturerID` = `l`.`LecturerID`)) join `slms`.`student` `st` on(`e`.`StudentID` = `st`.`StudentID`));

-- ---- vw_course_score_ranking ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_course_score_ranking` AS select `c`.`CourseID` AS `CourseID`,`c`.`CourseName` AS `CourseName`,`st`.`StudentID` AS `StudentID`,`st`.`F_Name` AS `F_Name`,`st`.`L_Name` AS `L_Name`,round(avg(`sub`.`Score`),2) AS `AvgScore`,rank() over ( partition by `c`.`CourseID` order by avg(`sub`.`Score`) desc) AS `RankInCourse` from ((((`slms`.`submission` `sub` join `slms`.`assessment` `a` on(`sub`.`AssessmentID` = `a`.`AssessmentID`)) join `slms`.`course` `c` on(`a`.`CourseID` = `c`.`CourseID`)) join `slms`.`student` `st` on(`sub`.`StudentID` = `st`.`StudentID`)) join `slms`.`enrollment` `e` on(`e`.`StudentID` = `st`.`StudentID` and `e`.`CourseID` = `c`.`CourseID`)) where `sub`.`IsActive` = 1 group by `c`.`CourseID`,`c`.`CourseName`,`st`.`StudentID`,`st`.`F_Name`,`st`.`L_Name`;

-- ---- vw_late_submissions ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_late_submissions` AS select `st`.`StudentID` AS `StudentID`,`st`.`F_Name` AS `F_Name`,`st`.`L_Name` AS `L_Name`,`c`.`CourseID` AS `CourseID`,`c`.`CourseName` AS `CourseName`,`a`.`AssessmentName` AS `AssessmentName`,`a`.`DueDate` AS `DueDate`,`sub`.`SubmissionDate` AS `SubmissionDate`,to_days(`sub`.`SubmissionDate`) - to_days(`a`.`DueDate`) AS `DaysLate`,rank() over ( partition by `c`.`CourseID` order by to_days(`sub`.`SubmissionDate`) - to_days(`a`.`DueDate`) desc) AS `LatenessRankInCourse` from (((`slms`.`submission` `sub` join `slms`.`assessment` `a` on(`sub`.`AssessmentID` = `a`.`AssessmentID`)) join `slms`.`course` `c` on(`a`.`CourseID` = `c`.`CourseID`)) join `slms`.`student` `st` on(`sub`.`StudentID` = `st`.`StudentID`)) where `sub`.`IsActive` = 1 and `sub`.`SubmissionDate` > `a`.`DueDate`;

-- ---- vw_lecturer_load ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_lecturer_load` AS select `l`.`LecturerID` AS `LecturerID`,`l`.`F_Name` AS `F_Name`,`l`.`L_Name` AS `L_Name`,count(distinct `c`.`CourseID`) AS `NumCourses`,count(distinct `e`.`StudentID`) AS `NumStudents` from ((`slms`.`lecturer` `l` left join `slms`.`course` `c` on(`l`.`LecturerID` = `c`.`LecturerID`)) left join `slms`.`enrollment` `e` on(`c`.`CourseID` = `e`.`CourseID`)) group by `l`.`LecturerID`;

-- ---- vw_lecturer_timetable ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_lecturer_timetable` AS select `l`.`LecturerID` AS `LecturerID`,`l`.`F_Name` AS `F_Name`,`l`.`L_Name` AS `L_Name`,`c`.`CourseID` AS `CourseID`,`c`.`CourseCode` AS `CourseCode`,`c`.`CourseName` AS `CourseName`,`s`.`SemesterName` AS `SemesterName`,`s`.`AcademicYear` AS `AcademicYear`,`t`.`DayOfWeek` AS `DayOfWeek`,`t`.`StartTime` AS `StartTime`,`t`.`EndTime` AS `EndTime`,`t`.`Room` AS `Room` from (((`slms`.`lecturer` `l` join `slms`.`course` `c` on(`l`.`LecturerID` = `c`.`LecturerID`)) join `slms`.`timetable` `t` on(`c`.`CourseID` = `t`.`CourseID`)) join `slms`.`semester` `s` on(`c`.`SemesterID` = `s`.`SemesterID`));

-- ---- vw_never_absent_students ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_never_absent_students` AS select `st`.`StudentID` AS `StudentID`,`st`.`F_Name` AS `F_Name`,`st`.`L_Name` AS `L_Name` from `slms`.`student` `st` where exists(select 1 from `slms`.`attendance` `att` where `att`.`StudentID` = `st`.`StudentID` limit 1) and !exists(select 1 from `slms`.`attendance` `att` where `att`.`StudentID` = `st`.`StudentID` and `att`.`Status` = 'Absent' limit 1);

-- ---- vw_student_final_grades ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_student_final_grades` AS select `x`.`StudentID` AS `StudentID`,`x`.`F_Name` AS `F_Name`,`x`.`L_Name` AS `L_Name`,`x`.`SemesterID` AS `SemesterID`,`x`.`SemesterName` AS `SemesterName`,`x`.`AcademicYear` AS `AcademicYear`,`x`.`CourseID` AS `CourseID`,`x`.`CourseName` AS `CourseName`,`x`.`CreditHours` AS `CreditHours`,`x`.`FinalGradePercent` AS `FinalGradePercent`,case when `x`.`FinalGradePercent` >= 90 then 'A+' when `x`.`FinalGradePercent` >= 80 then 'A' when `x`.`FinalGradePercent` >= 70 then 'B' when `x`.`FinalGradePercent` >= 60 then 'C' when `x`.`FinalGradePercent` >= 50 then 'D' else 'F' end AS `LetterGrade`,case when `x`.`FinalGradePercent` >= 80 then 4.0 when `x`.`FinalGradePercent` >= 70 then 3.0 when `x`.`FinalGradePercent` >= 60 then 2.0 when `x`.`FinalGradePercent` >= 50 then 1.0 else 0.0 end AS `GradePoint` from (select `g`.`StudentID` AS `StudentID`,`g`.`F_Name` AS `F_Name`,`g`.`L_Name` AS `L_Name`,`c`.`SemesterID` AS `SemesterID`,`s`.`SemesterName` AS `SemesterName`,`s`.`AcademicYear` AS `AcademicYear`,`c`.`CourseID` AS `CourseID`,`c`.`CourseName` AS `CourseName`,`c`.`CreditHours` AS `CreditHours`,round(sum(`g`.`Score` / `g`.`MaxScore` * `g`.`Weight`) / sum(`g`.`Weight`) * 100,2) AS `FinalGradePercent` from ((`slms`.`vw_course_grades` `g` join `slms`.`course` `c` on(`c`.`CourseID` = `g`.`CourseID`)) join `slms`.`semester` `s` on(`c`.`SemesterID` = `s`.`SemesterID`)) where `g`.`Score` is not null group by `g`.`StudentID`,`g`.`F_Name`,`g`.`L_Name`,`c`.`SemesterID`,`s`.`SemesterName`,`s`.`AcademicYear`,`c`.`CourseID`,`c`.`CourseName`,`c`.`CreditHours`) `x`;

-- ---- vw_student_gpa ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_student_gpa` AS select `y`.`StudentID` AS `StudentID`,`y`.`SemesterID` AS `SemesterID`,`y`.`SemesterName` AS `SemesterName`,`y`.`AcademicYear` AS `AcademicYear`,`y`.`SemesterGPA` AS `SemesterGPA`,round(sum(`y`.`QualityPoints`) over ( partition by `y`.`StudentID` order by `y`.`AcademicYear`,`y`.`SemesterName`) / sum(`y`.`SemesterCreditHours`) over ( partition by `y`.`StudentID` order by `y`.`AcademicYear`,`y`.`SemesterName`),2) AS `CGPA` from (select `vw_student_final_grades`.`StudentID` AS `StudentID`,`vw_student_final_grades`.`SemesterID` AS `SemesterID`,`vw_student_final_grades`.`SemesterName` AS `SemesterName`,`vw_student_final_grades`.`AcademicYear` AS `AcademicYear`,round(sum(`vw_student_final_grades`.`GradePoint` * `vw_student_final_grades`.`CreditHours`) / sum(`vw_student_final_grades`.`CreditHours`),2) AS `SemesterGPA`,sum(`vw_student_final_grades`.`GradePoint` * `vw_student_final_grades`.`CreditHours`) AS `QualityPoints`,sum(`vw_student_final_grades`.`CreditHours`) AS `SemesterCreditHours` from `slms`.`vw_student_final_grades` group by `vw_student_final_grades`.`StudentID`,`vw_student_final_grades`.`SemesterID`,`vw_student_final_grades`.`SemesterName`,`vw_student_final_grades`.`AcademicYear`) `y`;

-- ---- vw_student_timetable ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_student_timetable` AS select `st`.`StudentID` AS `StudentID`,`st`.`F_Name` AS `F_Name`,`st`.`L_Name` AS `L_Name`,`c`.`CourseCode` AS `CourseCode`,`c`.`CourseName` AS `CourseName`,`t`.`DayOfWeek` AS `DayOfWeek`,`t`.`StartTime` AS `StartTime`,`t`.`EndTime` AS `EndTime`,`t`.`Room` AS `Room` from (((`slms`.`enrollment` `e` join `slms`.`student` `st` on(`e`.`StudentID` = `st`.`StudentID`)) join `slms`.`course` `c` on(`e`.`CourseID` = `c`.`CourseID`)) join `slms`.`timetable` `t` on(`c`.`CourseID` = `t`.`CourseID`));

-- ---- vw_ungraded_submissions ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_ungraded_submissions` AS select `c`.`LecturerID` AS `LecturerID`,`c`.`CourseName` AS `CourseName`,`a`.`AssessmentName` AS `AssessmentName`,`st`.`F_Name` AS `F_Name`,`st`.`L_Name` AS `L_Name`,`sub`.`SubmissionID` AS `SubmissionID`,`sub`.`SubmissionDate` AS `SubmissionDate`,count(0) over ( partition by `sub`.`AssessmentID`) AS `UngradedCountForThisAssessment` from (((`slms`.`submission` `sub` join `slms`.`assessment` `a` on(`sub`.`AssessmentID` = `a`.`AssessmentID`)) join `slms`.`course` `c` on(`a`.`CourseID` = `c`.`CourseID`)) join `slms`.`student` `st` on(`sub`.`StudentID` = `st`.`StudentID`)) where `sub`.`IsActive` = 1 and `sub`.`Score` is null;

-- ---- vw_upcoming_deadlines_ranked ----
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `slms`.`vw_upcoming_deadlines_ranked` AS select `c`.`CourseID` AS `CourseID`,`c`.`CourseName` AS `CourseName`,`a`.`AssessmentName` AS `AssessmentName`,`a`.`DueDate` AS `DueDate`,to_days(`a`.`DueDate`) - to_days(curdate()) AS `DaysRemaining`,rank() over ( partition by `a`.`CourseID` order by `a`.`DueDate`) AS `DeadlineRankInCourse` from (`slms`.`assessment` `a` join `slms`.`course` `c` on(`a`.`CourseID` = `c`.`CourseID`)) where `a`.`DueDate` >= curdate();
